variables:
  CI_SERVER_URL: http://makebe-gitlab

stages:
  - build
  - deploy

build:
  stage: build
  image: node:20.9.0
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/
  tags:
    - docker

deploy:
  stage: deploy
  image: docker:25.0.2
  before_script:
    - apk update && apk add --no-cache rsync openssh-client sshpass
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DOCKER_NETWORK" >> ~/.ssh/known_hosts
  script:
    - |
      sshpass -p "$DOCKER_PASSWORD" ssh -o StrictHostKeyChecking=no "$DOCKER_USER@$DOCKER_NETWORK" "
      sudo docker pull makebe:latest || true
      sudo docker build -t makebe:latest .
      sudo docker stop makebe || true
      sudo docker rm makebe || true
      sudo docker run -d --name makebe -p 8081:80 -v /etc/localtime:/etc/localtime:ro makebe:latest
      sudo docker network connect dockercompose_makebe-rede makebe || true
      sudo docker cp makebe:/app /home/makebe-user/sites/makebe
      "
  tags:
    - docker
  only:
    - main
