FROM node:20.9.0 AS build-env

WORKDIR /nginx_front-end

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-env /nginx_front-end/out .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
